### ISSUE TITLE
How2 integrate animations

### ISSUE THREAD

**Issue by Ws2812B** [bitluni/bitluniHomeAutomation#4]
I would be really interested to know how2 create or implement existing animations into the library. Could you explain it somehow?

**Comment by bitluni** [comment]
If you are somehow familiar with c++
you could take a look
at LedFunction.h
You need to derive from the class LedFunction and implement the init and render methods.
WaveFunction.h might be an inspiration

also you need to add the function to the webserver int the setup just like
`
  server.on("/wave", [](){
    server.send(200, "text/plain", "wave");
    WaveFunction *f = new WaveFunction();
    f->init(server);
    checkFadeAndSetLedFunction(f);
  });`

**Comment by Ws2812B** [comment]
Now I spent a big part of a day and one night on trying to implement an animation. It is the rainbowCycle void of strandtest(example included in the Neo Pixel Library). Your Sketch/Library already includes a rainbow but the one of the strandtest looks better for my application because of the high density of the LEDs and the shorter length and I want to know how2 generally make/integrate animations for your really well made library. All I get with my try is crazy blinking of the LEDs. 
Animation, that I want to include:

`void rainbowCycle(uint8_t wait) {
  uint16_t i, j;

  for(j=0; j<256*5; j++) { // 5 cycles of all colors on wheel
    for(i=0; i< strip.numPixels(); i++) {
      strip.setPixelColor(i, Wheel(((i * 256 / strip.numPixels()) + j) & 255));
    }
    strip.show();
    delay(wait);
  }
}`

Parts that i am using:
-144LED/m Strip. In my case 77 LEDs
-ESP8266 Node Mcu V3 (no compatibility issues to D1 Mini)
It would be really really really nice of you and helpful for me if you could make an example code how to include this animation or tell me what I did wrong or explain a bit more detailed how to create/integrate animations. But I think trying to explain what I did wrong would take you the most time. 
This is the Code of Test.h and what I included in setup():

`/*
Released under Creative Commons Attribution 4.0
by bitluni 2016
https://creativecommons.org/licenses/by/4.0/
Attribution means you can use it however you like as long you
mention that it's base on my stuff.
I'll be pleased if you'd do it by sharing http://youtube.com/bitlunislab
*/

#include <Adafruit_NeoPixel.h>
#include <math.h>
#include "LedFunction.h"


int j = 0;
int rw = 0;
int gw = 0;
int bw = 0;

int Wheelr(int WheelPos) {        //delivers Red val
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return (255 - WheelPos * 3);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return (0);
  }
  WheelPos -= 170;
  return (WheelPos * 3);
}

int Wheelg(int WheelPos) {        //delivers Green val
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return (0);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return (WheelPos * 3);
  }
  WheelPos -= 170;
  return (255 - WheelPos * 3);
}

int Wheelb(int WheelPos) {	    //delivers Blue val
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return (WheelPos * 3);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return (255 - WheelPos * 3);
  }
  WheelPos -= 170;
  return (0);
}

class Test: public LedFunction
{
  public:
  long sinTab[256];
  uint8_t rgb[3] = {0, 0, 0};
  int start;
  Test()
  {

  }

  virtual bool init(ESP8266WebServer &server)
  {
    if(!loadRGBValues(server, rgb))
      return false;
  }
  
  virtual void render()
  {
  if (j<1280) { j++; } else { j = 0; }     // in the original version of the animation that I want to implement is this a for() loop, which determines how long it will stays in this loop and renders the animation.
										   // here is the for() loop the loop() in the main file(bitluniHomeAutomation.ino) but the counter(in this case j) is necessary for the animation to work. So i simulated
										   //this counter with this line.
    for(int i = 0; i < state->count; i++)
    {

		rw = Wheelr(j);				//converts the values of the Wheel from ints to uint8_t
		gw = Wheelg(j);
		bw = Wheelb(j);
		uint8_t rvv = rw;
		uint8_t gvv = gw;
		uint8_t bvv = bw;
      state->setRgb(i, rvv,gvv,bvv);   //nothing to say about that
    }
  }
};

//some stuff is programmed a bit dirty but I wanted to write this Code simple to not make any simple mistakes.`

`  server.on("/Test", [](){
    server.send(200, "text/plain", "Test");
    Test *f = new Test();
    f->init(server);
    checkFadeAndSetLedFunction(f);
  });`

**Comment by Ws2812B** [comment]
`Test
hal`

**Comment by Ws2812B** [comment]
'Now I spent a big part of a day and one night on trying to implement an animation. It is the rainbowCycle void of strandtest(example included in the Neo Pixel Library). Your Sketch/Library already includes a rainbow but the one of the strandtest looks better for my application because of the high density of the LEDs and the shorter length and I want to know how2 generally make/integrate animations for your really well made library. All I get with my try is crazy blinking of the LEDs. 
Animation, that I want to include:

`
void rainbowCycle(uint8_t wait) {
  uint16_t i, j;

  for(j=0; j<256*5; j++) { // 5 cycles of all colors on wheel
    for(i=0; i< strip.numPixels(); i++) {
      strip.setPixelColor(i, Wheel(((i * 256 / strip.numPixels()) + j) & 255));
    }
    strip.show();
    delay(wait);
  }
}
`

Parts that i am using:
-144LED/m Strip. In my case 77 LEDs
-ESP8266 Node Mcu V3 (no compatibility issues to D1 Mini)
It would be really really really nice of you and helpful for me if you could make an example code how to include this animation or tell me what I did wrong or explain a bit more detailed how to create/integrate animations. But I think trying to explain what I did wrong would take you the most time. 
This is the Code of Test.h and what I included in setup():

`
/*
Released under Creative Commons Attribution 4.0
by bitluni 2016
https://creativecommons.org/licenses/by/4.0/
Attribution means you can use it however you like as long you
mention that it's base on my stuff.
I'll be pleased if you'd do it by sharing http://youtube.com/bitlunislab
*/

#include <Adafruit_NeoPixel.h>
#include <math.h>
#include "LedFunction.h"


int j = 0;
int rw = 0;
int gw = 0;
int bw = 0;

int Wheelr(int WheelPos) {        //delivers Red val
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return (255 - WheelPos * 3);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return (0);
  }
  WheelPos -= 170;
  return (WheelPos * 3);
}

int Wheelg(int WheelPos) {        //delivers Green val
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return (0);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return (WheelPos * 3);
  }
  WheelPos -= 170;
  return (255 - WheelPos * 3);
}

int Wheelb(int WheelPos) {	    //delivers Blue val
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return (WheelPos * 3);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return (255 - WheelPos * 3);
  }
  WheelPos -= 170;
  return (0);
}

class Test: public LedFunction
{
  public:
  long sinTab[256];
  uint8_t rgb[3] = {0, 0, 0};
  int start;
  Test()
  {

  }

  virtual bool init(ESP8266WebServer &server)
  {
    if(!loadRGBValues(server, rgb))
      return false;
  }
  
  virtual void render()
  {
  if (j<1280) { j++; } else { j = 0; }     // in the original version of the animation that I want to implement is this a for() loop, which determines how long it will stays in this loop and renders the animation.
										   // here is the for() loop the loop() in the main file(bitluniHomeAutomation.ino) but the counter(in this case j) is necessary for the animation to work. So i simulated
										   //this counter with this line.
    for(int i = 0; i < state->count; i++)
    {

		rw = Wheelr(j);				//converts the values of the Wheel from ints to uint8_t
		gw = Wheelg(j);
		bw = Wheelb(j);
		uint8_t rvv = rw;
		uint8_t gvv = gw;
		uint8_t bvv = bw;
      state->setRgb(i, rvv,gvv,bvv);   //nothing to say about that
    }
  }
};

//some stuff is programmed a bit dirty but I wanted to write this Code simple to not make any simple mistakes.

`

`  server.on("/Test", [](){
    server.send(200, "text/plain", "Test");
    Test *f = new Test();
    f->init(server);
    checkFadeAndSetLedFunction(f);
  });
`'

**Comment by Ws2812B** [comment]
`Now I spent a big part of a day and one night on trying to implement an animation. It is the rainbowCycle void of strandtest(example included in the Neo Pixel Library). Your Sketch/Library already includes a rainbow but the one of the strandtest looks better for my application because of the high density of the LEDs and the shorter length and I want to know how2 generally make/integrate animations for your really well made library. All I get with my try is crazy blinking of the LEDs. 
Animation, that I want to include:

`
void rainbowCycle(uint8_t wait) {
  uint16_t i, j;

  for(j=0; j<256*5; j++) { // 5 cycles of all colors on wheel
    for(i=0; i< strip.numPixels(); i++) {
      strip.setPixelColor(i, Wheel(((i * 256 / strip.numPixels()) + j) & 255));
    }
    strip.show();
    delay(wait);
  }
}
`

Parts that i am using:
-144LED/m Strip. In my case 77 LEDs
-ESP8266 Node Mcu V3 (no compatibility issues to D1 Mini)
It would be really really really nice of you and helpful for me if you could make an example code how to include this animation or tell me what I did wrong or explain a bit more detailed how to create/integrate animations. But I think trying to explain what I did wrong would take you the most time. 
This is the Code of Test.h and what I included in setup():

`
/*
Released under Creative Commons Attribution 4.0
by bitluni 2016
https://creativecommons.org/licenses/by/4.0/
Attribution means you can use it however you like as long you
mention that it's base on my stuff.
I'll be pleased if you'd do it by sharing http://youtube.com/bitlunislab
*/

#include <Adafruit_NeoPixel.h>
#include <math.h>
#include "LedFunction.h"


int j = 0;
int rw = 0;
int gw = 0;
int bw = 0;

int Wheelr(int WheelPos) {        //delivers Red val
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return (255 - WheelPos * 3);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return (0);
  }
  WheelPos -= 170;
  return (WheelPos * 3);
}

int Wheelg(int WheelPos) {        //delivers Green val
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return (0);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return (WheelPos * 3);
  }
  WheelPos -= 170;
  return (255 - WheelPos * 3);
}

int Wheelb(int WheelPos) {	    //delivers Blue val
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return (WheelPos * 3);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return (255 - WheelPos * 3);
  }
  WheelPos -= 170;
  return (0);
}

class Test: public LedFunction
{
  public:
  long sinTab[256];
  uint8_t rgb[3] = {0, 0, 0};
  int start;
  Test()
  {

  }

  virtual bool init(ESP8266WebServer &server)
  {
    if(!loadRGBValues(server, rgb))
      return false;
  }
  
  virtual void render()
  {
  if (j<1280) { j++; } else { j = 0; }     // in the original version of the animation that I want to implement is this a for() loop, which determines how long it will stays in this loop and renders the animation.
										   // here is the for() loop the loop() in the main file(bitluniHomeAutomation.ino) but the counter(in this case j) is necessary for the animation to work. So i simulated
										   //this counter with this line.
    for(int i = 0; i < state->count; i++)
    {

		rw = Wheelr(j);				//converts the values of the Wheel from ints to uint8_t
		gw = Wheelg(j);
		bw = Wheelb(j);
		uint8_t rvv = rw;
		uint8_t gvv = gw;
		uint8_t bvv = bw;
      state->setRgb(i, rvv,gvv,bvv);   //nothing to say about that
    }
  }
};

//some stuff is programmed a bit dirty but I wanted to write this Code simple to not make any simple mistakes.

`

`  server.on("/Test", [](){
    server.send(200, "text/plain", "Test");
    Test *f = new Test();
    f->init(server);
    checkFadeAndSetLedFunction(f);
  });
``

**Comment by Ws2812B** [comment]
Now I spent a big part of a day and one night on trying to implement an animation. It is the rainbowCycle void of strandtest(example included in the Neo Pixel Library). Your Sketch/Library already includes a rainbow but the one of the strandtest looks better for my application because of the high density of the LEDs and the shorter length and I want to know how2 generally make/integrate animations for your really well made library. All I get with my try is crazy blinking of the LEDs. 
Animation, that I want to include:

`
void rainbowCycle(uint8_t wait) {
  uint16_t i, j;

  for(j=0; j<256*5; j++) { // 5 cycles of all colors on wheel
    for(i=0; i< strip.numPixels(); i++) {
      strip.setPixelColor(i, Wheel(((i * 256 / strip.numPixels()) + j) & 255));
    }
    strip.show();
    delay(wait);
  }
}
`

Parts that i am using:
-144LED/m Strip. In my case 77 LEDs
-ESP8266 Node Mcu V3 (no compatibility issues to D1 Mini)
It would be really really really nice of you and helpful for me if you could make an example code how to include this animation or tell me what I did wrong or explain a bit more detailed how to create/integrate animations. But I think trying to explain what I did wrong would take you the most time. 
This is the Code of Test.h and what I included in setup():

**Comment by Ws2812B** [comment]
Now I spent a big part of a day and one night on trying to implement an animation. It is the rainbowCycle void of strandtest(example included in the Neo Pixel Library). Your Sketch/Library already includes a rainbow but the one of the strandtest looks better for my application because of the high density of the LEDs and the shorter length and I want to know how2 generally make/integrate animations for your really well made library. All I get with my try is crazy blinking of the LEDs. 
Animation, that I want to include:

`void rainbowCycle(uint8_t wait) {
  uint16_t i, j;

  for(j=0; j<256*5; j++) { // 5 cycles of all colors on wheel
    for(i=0; i< strip.numPixels(); i++) {
      strip.setPixelColor(i, Wheel(((i * 256 / strip.numPixels()) + j) & 255));
    }
    strip.show();
    delay(wait);
  }
}
`


Parts that i am using:
-144LED/m Strip. In my case 77 LEDs
-ESP8266 Node Mcu V3 (no compatibility issues to D1 Mini)
It would be really really really nice of you and helpful for me if you could make an example code how to include this animation or tell me what I did wrong or explain a bit more detailed how to create/integrate animations. But I think trying to explain what I did wrong would take you the most time. 
This is the Code of Test.h and what I included in setup():

**Comment by Ws2812B** [comment]
Now I spent a big part of yesterday and this night on trying to get it to work. But the only thing I got was crazy Blinking. The animations I tried to include was the rainbowCycle void of the strandtest example sketch of the Adafuit Neopixel Library. Your well coded Sketch/Library already includes a rainbow but the one out of the strandtest exaple sketch looks better for my apllication, because i have a LED Strip with a density of 144LEDs/m and i use only 50cm of that.
Here is the code of the original animation. I tried to format it as a Code but it just didn't work.

void rainbowCycle(uint8_t wait) {
  uint16_t i, j;

  for(j=0; j<256*5; j++) { // 5 cycles of all colors on wheel
    for(i=0; i< strip.numPixels(); i++) {
      strip.setPixelColor(i, Wheel(((i * 256 / strip.numPixels()) + j) & 255));
    }
    strip.show();
    delay(wait);
  }
}

It would be really really really nice if you could make an example Code with this animation how to integrate animations or explain how to generally integrate/create animations or explain, what I did wrong in Test.h(attached as .txt) but I think explaining, what I did wrong would be the most time-consuming.

Thanks in Advance
[Test.h.txt](https://github.com/bitluni/bitluniHomeAutomation/files/1259247/Test.h.txt)

**Comment by Ws2812B** [comment]
Ok. Now I got it to work. The Solution are 3 voids, that return the Red, Green and Blue values of a uint32_t color. I had to create "fake" Neopixel strip named "stripp" to create the uint32_t colors in the Wheel. I'm sure there would be another wy to solve this problem but i'm not so competent in coding.

I will post the code here soon after a bit fine tuning and a few optimazations.

**Comment by Ws2812B** [comment]
`/*
Released under Creative Commons Attribution 4.0
by bitluni 2016
https://creativecommons.org/licenses/by/4.0/
Attribution means you can use it however you like as long you
mention that it's base on my stuff.
I'll be pleased if you'd do it by sharing http://youtube.com/bitlunislab
*/

#include "LedFunction.h"
#include <Adafruit_NeoPixel.h>



class Test: public LedFunction
{
  public:
  Adafruit_NeoPixel stripp = Adafruit_NeoPixel(77, D4, NEO_GRB + NEO_KHZ800);

  int j = 0;
  
  // Returns the Red component of a 32-bit color
    uint8_t Red(uint32_t color)
    {
        return (color >> 16) & 0xFF;
    }
 
    // Returns the Green component of a 32-bit color
    uint8_t Green(uint32_t color)
    {
        return (color >> 8) & 0xFF;
    }
 
    // Returns the Blue component of a 32-bit color
    uint8_t Blue(uint32_t color)
    {
        return color & 0xFF;
    }
	
	uint32_t Wheel(byte WheelPos)
    {
        WheelPos = 255 - WheelPos;
        if(WheelPos < 85)
        {
            return stripp.Color(255 - WheelPos * 3, 0, WheelPos * 3);
        }
        else if(WheelPos < 170)
        {
            WheelPos -= 85;
            return stripp.Color(0, WheelPos * 3, 255 - WheelPos * 3);
        }
        else
        {
            WheelPos -= 170;
            return stripp.Color(WheelPos * 3, 255 - WheelPos * 3, 0);
        }
    }
  
  
  Test()
  {    
  }

  virtual void render()
  {
	  delay(15); //I'm trying to define this value by an extra "delay" argument in the future
	  j++;
	  if (j > 256) { j = 0; }
    for(int i = 0; i < state->count; i++) {
      state->setRgb(i,Red(Wheel(((i * 256 / stripp.numPixels()) + j) & 255)),Green(Wheel(((i * 256 / stripp.numPixels()) + j) & 255)),Blue(Wheel(((i * 256 / stripp.numPixels()) + j) & 255)));
	}
  }
};

`

I don't know why, but if I'm trying to name it "Regenbogen" it doesn't work.

**Comment by Ws2812B** [comment]
This Code works.
[Test.h.txt](https://github.com/bitluni/bitluniHomeAutomation/files/1268085/Test.h.txt)
